plugins: # List of plugins of use on application
  # - serverless-offline # Get your serverless configuration and run the server local
  - serverless-plugin-typescript-express # Help us with configuration typescript on serverless

service: zelp-motovolt-authentication

provider:
  name: aws
  endpointType: REGIONAL
  runtime: nodejs10.x
  stage: dev
  region: us-east-2
  memorySize: 128
  environment: 
    REGISTEREDFRAMEIDFORMOBILEURL: https://fwvwsm1jsh.execute-api.us-east-2.amazonaws.com/yantra/validateph
    CREATEUSERURL: https://q6sm9vkbn2.execute-api.us-east-2.amazonaws.com/dev/user/
    WEBAPPSITEURL: http://localhost:3000
functions:
  preSignUp:
    handler: src/functions.preSignUp
    events: 
      - http: 
          path: /preSignUp
          method: ANY
          cors: true
  postConfirmation:
    handler: src/functions.postConfirmation
    events: 
      - http: 
          path: /postConfirmation
          method: ANY
          cors: true
  webAppForgotPassword:
    handler: src/functions.webAppForgotPassword
    events: 
      - http: 
          path: /webAppForgotPassword
          method: ANY
          cors: true
  createWebAppUser:
    handler: src/createWebAppUser.createWebAppUser
    events: 
      - http: 
          path: /createWebAppUser
          method: POST
          cors: true